---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.adversity.dev
  resources:
  - ipblocklists
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.adversity.dev
  resources:
  - ipblocklists/finalizers
  verbs:
  - update
- apiGroups:
  - security.adversity.dev
  resources:
  - ipblocklists/status
  verbs:
  - get
  - patch
  - update
